name: sensors
description: A new Flutter project.

flutter:
  plugin:
    androidPackage: io.flutter.plugins.sensors
    iosPrefix: FLT
    pluginClass: SensorsPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  e2e: ^0.2.0
  mockito: ^4.1.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.6.7 <2.0.0"
